# å½“å‰ç‰ˆæœ¬ | Theme Version
Hexo: "2.1"

#è¯­è¨€ | Language
# en | zh-Hans
#è¯·åœ¨hexoæ–‡ä»¶ä¸‹çš„"_config.yml"ä¿®æ”¹language
language: zh-Hans

# ç½‘ç«™æ ‡é¢˜ | Title
logo_title: YeChang Zhang

# åˆå§‹åŒ–é£æ ¼ | Default Style "black/light"
style: black
#style: light

#SEOä¼˜åŒ–

## ç½‘ç«™æè¿°
description: å˜¿ï¼Œæˆ‘æ˜¯å¼ ä¸šæ˜Œï½è¿™æ˜¯æˆ‘çš„ç½‘ç«™ï¼Œç”¨äºå±•ç¤ºæˆ‘çš„åšå®¢ï¼Œæ¬¢è¿è®¿é—®ï¼

## ç½‘ç«™å…³é”®è¯ï¼šç”¨è‹±æ–‡é€—å·åˆ†å‰²
keywords: Blog,Theme,å¼ ä¸šæ˜Œ,YeChang Zhang

# é¦–é¡µURL | Your URL
link: Your_URL

#æ ‡è¯­ | Your Slogan
words: JavaScript Vue React Vant Uni-App Next Antd-Design-Pro Antd-Design-Vue

# ä½ çš„æ˜µç§° | Your Name
author: YeChang Zhang

# ä¸­å¿ƒå›¾æ ‡é€‰æ‹©ç”·å¥³æˆ–è€…è‡ªå®šä¹‰ | Gender
gender: /img/male.png #/img/female.png

# ç«™ç‚¹å°å›¾æ ‡åœ°å€ | Small Icon of Your Site
favicon: /img/favicon.ico

# èœå•æ é…ç½® | Nav Bar Settings
menu:
  å…³äºæˆ‘ğŸ‘€: /about
  è®¿é—®ä¸»ç«™ğŸ‰: https://
  GitHubğŸ’: https://github.com/13725102796
  tags: /tags/ || tags
  categories: /categories/ || th


# ç«™å†…å…³é”®è¯æœç´¢ | Local Search
search:
 enable: true
 path: search.xml
 field: post
 # onload: true

# è¯„è®ºç³»ç»Ÿ | Comments
## åšäº†åŸŸåé™åˆ¶ï¼Œè¯·æ”¹æˆè‡ªå·±çš„ KEY
## è‹¥å…³é—­valine è®¾ç½®enableä¸ºfalseâˆ‚
valine:
  enable: true
  appId: 
  appKey: 

# visitors count
counter:
  enable: true

highlight:
  enable: true
